spring:
  application:
    name: tempo
  flyway:
    enabled: true
    clean-on-validation-error: true

logging:
  level:
    org.springframework: ERROR
    org.hibernate: ERROR
    org.flywaydb: ERROR
    org.postgresql: ERROR
    org.testcontainers: ERROR
    io.awspring.cloud: ERROR
